import type { Metadata } from 'next';
import { REM } from 'next/font/google';
import Provider from './provider';
import './globals.css';

const rem = REM({ subsets: ['latin'] });

// 메타데이터 수정
export const metadata: Metadata = {
  title: `Juhee's Portfolio`,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={rem.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
